apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanagement-api-deployment
  namespace: taskmanagement
  labels:
    app: taskmanagement-api
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanagement-api
  template:
    metadata:
      labels:
        app: taskmanagement-api
        tier: backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: taskmanagement-api
        image: taskmanagement-api:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: taskmanagement-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: taskmanagement-config
              key: ASPNETCORE_URLS
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: taskmanagement-secrets
              key: CONNECTION_STRING
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
      imagePullSecrets:
      - name: sre-jfrog-artifactory
      volumes:
      - name: logs-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: taskmanagement-api-service
  namespace: taskmanagement
  labels:
    app: taskmanagement-api
spec:
  selector:
    app: taskmanagement-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
