apiVersion: v1
kind: ConfigMap
metadata:
  name: taskmanagement-config
  namespace: taskmanagement
data:
  # API configuration
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  
  # Frontend configuration
  REACT_APP_API_URL: "http://taskmanagement-api-service/api"
  
  # Logging configuration
  LOG_LEVEL: "Information"
