apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanagement-frontend-deployment
  namespace: taskmanagement
  labels:
    app: taskmanagement-frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanagement-frontend
  template:
    metadata:
      labels:
        app: taskmanagement-frontend
        tier: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: taskmanagement-frontend
        image: taskmanagement-frontend:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 8080
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: taskmanagement-config
              key: REACT_APP_API_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      imagePullSecrets:
      - name: sre-jfrog-artifactory
      initContainers:
      - name: wait-for-api
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z taskmanagement-api-service 80; do echo waiting for api; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: taskmanagement-frontend-service
  namespace: taskmanagement
  labels:
    app: taskmanagement-frontend
spec:
  selector:
    app: taskmanagement-frontend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
