apiVersion: v1
kind: Service
metadata:
  name: taskmanagement-frontend-service
  namespace: taskmanagement
  labels:
    app: taskmanagement-frontend
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: taskmanagement-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: taskmanagement-frontend-service-nodeport
  namespace: taskmanagement
  labels:
    app: taskmanagement-frontend
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: taskmanagement-frontend
