apiVersion: v1
kind: Secret
metadata:
  name: taskmanagement-secrets
  namespace: taskmanagement
type: Opaque
data:
  # SQLite connection string (base64 encoded)
  # "Data Source=/app/data/taskmanagement.db"
  CONNECTION_STRING: RGF0YSBTb3VyY2U9L2FwcC9kYXRhL3Rhc2ttYW5hZ2VtZW50LmRi
