CREATE TABLE "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EntityType" character varying(100) NOT NULL,
    "EntityId" text NOT NULL,
    "Action" character varying(50) NOT NULL,
    "UserId" integer,
    "Summary" character varying(500) NOT NULL,
    "Details" text,
    "IpAddress" character varying(45),
    "UserAgent" character varying(500),
    "RequestPath" character varying(200),
    "HttpMethod" character varying(10),
    "ResponseStatusCode" integer,
    "ExecutionTimeMs" bigint,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    "Metadata" text,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Color" character varying(7) NOT NULL DEFAULT '#007bff',
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" character varying(255) NOT NULL,
    "PhoneNumber" character varying(20),
    "Department" character varying(100),
    "UserRole" integer NOT NULL DEFAULT 2,
    "AccountStatus" integer NOT NULL DEFAULT 0,
    "LastLoginAt" timestamp with time zone,
    "RefreshToken" character varying(255),
    "RefreshTokenExpiryTime" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Tasks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "Status" integer NOT NULL DEFAULT 0,
    "Priority" integer NOT NULL DEFAULT 1,
    "DueDate" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    "UserId" integer NOT NULL,
    "CategoryId" integer,
    "AssignedUserId" integer,
    CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tasks_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Tasks_Users_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_Tasks_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskComments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Content" character varying(2000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    "TaskId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_TaskComments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskComments_Tasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES "Tasks" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskComments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TaskActivities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ActivityType" integer NOT NULL,
    "Description" character varying(500),
    "OldValue" character varying(100),
    "NewValue" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    "TaskId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_TaskActivities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskActivities_Tasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES "Tasks" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskActivities_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AuditLogs_EntityType_EntityId" ON "AuditLogs" ("EntityType", "EntityId");
CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
CREATE INDEX "IX_AuditLogs_Action" ON "AuditLogs" ("Action");
CREATE INDEX "IX_AuditLogs_CreatedAt" ON "AuditLogs" ("CreatedAt");
CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
CREATE INDEX "IX_Tasks_AssignedUserId" ON "Tasks" ("AssignedUserId");
CREATE INDEX "IX_Tasks_CategoryId" ON "Tasks" ("CategoryId");
CREATE INDEX "IX_Tasks_UserId" ON "Tasks" ("UserId");
CREATE INDEX "IX_TaskComments_TaskId" ON "TaskComments" ("TaskId");
CREATE INDEX "IX_TaskComments_UserId" ON "TaskComments" ("UserId");
CREATE INDEX "IX_TaskActivities_TaskId" ON "TaskActivities" ("TaskId");
CREATE INDEX "IX_TaskActivities_UserId" ON "TaskActivities" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250903140000_InitialCreate', '8.0.0');